version: '3.8'

services:
  bot-prod:
    image: ghcr.io/audiosutras/feed_bot:latest
    command: sh -c "poetry install --no-interaction --only=main && poetry run bot"
    restart: always
    environment:
      - PROD_ENV=True
      - BOT_TOKEN=${BOT_TOKEN}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - MONGODB_URI=mongodb://root:feed_bot@mongo-prod:27017/
    depends_on:
      - mongo-prod
  mongo-prod:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=feed_bot
