version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-dev
    develop:
      watch:
        - action: sync+restart
          path: ./feed_bot
          target: /code/feed_bot
        - action: rebuild
          path: pyproject.toml
    command: sh -c "poetry install --no-interaction --only=main && poetry run bot"
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - MONGODB_URI=mongodb://root:feed_bot@mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=feed_bot
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
