version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - AFFILIATE_BOT_TOKEN=${AFFILIATE_BOT_TOKEN}
      - PYTHONFAULTHANDLER=1
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=random
      - PIP_NO_CACHE_DIR=off
      - PIP_DISABLE_PIP_VERSION_CHECK=on
      - PIP_DEFAULT_TIMEOUT=100
      - POETRY_VERSION=1.7.1

    command: 'poetry run bot'
