version: '3.8'

services:
  bot:
    image: ghcr.io/audiosutras/feed_bot:latest
    command: sh -c "poetry install --no-interaction --only=main && poetry run bot"
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URI=mongodb://root:feed_bot@mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=feed_bot
